apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: rajeshgalipelli089/rail-app-web
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: budget_app_development

---
apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  type: NodePort
  selector:
    app: rails-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
